services:
  qdrant:
    image: qdrant/qdrant:v1.18
    container_name: study-qdrant
    volumes:
      - qdrant_data:/qdrant/storage
      - ./qdrant/config.yaml:/qdrant/config.yaml
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - study-net

  n8n:
    image: n8nio/n8n:latest
    container_name: study-n8n
    environment:
      N8N_HOST: nonalternating-glaucomatous-necole.ngrok-free.dev
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://nonalternating-glaucomatous-necole.ngrok-free.dev
      N8N_METRICS: false
      N8N_BLOCK_ENV_ACCESS_IN_NODE: false
      N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN: true
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_OWNER_ID: ${TELEGRAM_OWNER_ID}
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/workflows
    networks:
      - study-net

  backend:
    build: ./backend
    container_name: study-backend
    environment:
      
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      GROQ_API_KEY: ${GROQ_API_KEY}
      GROQ_CHAT_MODEL: ${GROQ_CHAT_MODEL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL}
      TTS_MODEL: ${TTS_MODEL}
      N8N_WEBHOOK_URL: http://n8n:5678/webhook
    ports:
      - "8000:8000"
    volumes:
      - ./documents:/documents
      - ./backend:/app
      - /home/daviuk:/home/daviuk:ro
      - ./podcasts:/app/podcasts
    depends_on:
      qdrant:
        condition: service_started
    networks:
      - study-net

  ngrok:
    image: ngrok/ngrok:latest
    container_name: study-ngrok
    command: http n8n:5678 --url=https://${NGROK_DOMAIN}
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    depends_on:
      - n8n
    networks:
      - study-net

volumes:
  qdrant_data:
  n8n_data:

networks:
  study-net:
    driver: bridge
